"""Changed cascade

Revision ID: c0ece582f89c
Revises: 20e37947faab
Create Date: 2020-03-25 17:59:41.593060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ece582f89c'
down_revision = '20e37947faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
