# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import twitter_clone_pb2 as proto_dot_twitter__clone__pb2


class TweetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllTweets = channel.unary_stream(
        '/TweetService/GetAllTweets',
        request_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
        response_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
        )
    self.GetTweets = channel.unary_stream(
        '/TweetService/GetTweets',
        request_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
        response_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
        )
    self.CreateTweet = channel.unary_unary(
        '/TweetService/CreateTweet',
        request_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
        response_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
        )
    self.RemoveTweet = channel.unary_unary(
        '/TweetService/RemoveTweet',
        request_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
        response_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
        )
    self.EditTweet = channel.unary_unary(
        '/TweetService/EditTweet',
        request_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
        response_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
        )


class TweetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllTweets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTweets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllTweets': grpc.unary_stream_rpc_method_handler(
          servicer.GetAllTweets,
          request_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
          response_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
      ),
      'GetTweets': grpc.unary_stream_rpc_method_handler(
          servicer.GetTweets,
          request_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
          response_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
      ),
      'CreateTweet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTweet,
          request_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
          response_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
      ),
      'RemoveTweet': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveTweet,
          request_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
          response_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
      ),
      'EditTweet': grpc.unary_unary_rpc_method_handler(
          servicer.EditTweet,
          request_deserializer=proto_dot_twitter__clone__pb2.Tweet.FromString,
          response_serializer=proto_dot_twitter__clone__pb2.Tweet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TweetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
